[phases.setup]
nixPkgs = ["php82", "php82.extensions.gd", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php artisan key:generate"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"

